### ISSUE TITLE
send from mail list

### ISSUE THREAD

**Issue by fdciabdul** [fardog/nodemailer-cli#13]
I have mail list from text file , but how to bulk send with this package ?

**Comment by fardog** [comment]
this library doesn't have any bulk send capability; it was written for one-off sends in scripts or the like. if you want to do a bulk send with it, you could script something which iterated the file and called this utility one for each recipient; however i doubt this is the right tool for the job in that case. [this tool](https://www.npmjs.com/package/bulk-mail-cli) (not maintained nor endorsed by me, I've never used it) might work for you.

closing this as `wontfix` since it's outside of this package's scope.
